--Reference data for Roles
INSERT INTO ROLES VALUES (1, 'Project Manager',  'Manager');
INSERT INTO ROLES VALUES (2, 'Project Developer',  'Developer');

--Reference data for tech stack
INSERT INTO TECHSTACK_ENTITY VALUES (1, 'JAVA');
INSERT INTO TECHSTACK_ENTITY VALUES (2, 'PYTHON');
INSERT INTO TECHSTACK_ENTITY VALUES (3, 'ANGULAR');
INSERT INTO TECHSTACK_ENTITY VALUES (4, 'REACT');
INSERT INTO TECHSTACK_ENTITY VALUES (5, 'C++');
INSERT INTO TECHSTACK_ENTITY VALUES (6, 'CUCUMBER');
INSERT INTO TECHSTACK_ENTITY VALUES (7, 'JAVA SCRIPT');
INSERT INTO TECHSTACK_ENTITY VALUES (8, 'NODE JS');
INSERT INTO TECHSTACK_ENTITY VALUES (9, 'SPRING BOOT');
INSERT INTO TECHSTACK_ENTITY VALUES (10, 'SCALA');
INSERT INTO TECHSTACK_ENTITY VALUES (11, 'HADOOP');
